version: "3"
services:
  web:
    environment:
      - PORT=8080
      - ES_HOST=http://elasticsearch:9200
      - DEBUG=debug,error
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
  elasticsearch:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9300:9300"
      - "9200:9200"
volumes:
  esdata:
